version: '2'

volumes:
  postgresql:
  postgresql_data:

services:
  postgresd:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    restart: always
    ports:
      - "6666:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    links:
      - postgresd:postgresd
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    restart: unless-stopped
    ports:
      - "9999:9999"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "1337:1337"
    links:
      - api:api

  proxy:
    image: nginx:latest
    ports:
      - "1234:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - api:api
      - frontend:frontend

  # influxdbData:
  #   image: busybox
  #   volumes:
  #     - ./data/influxdb:/data
  #
  # influxdb:
  #   image: tutum/influxdb:0.9
  #   restart: always
  #   environment:
  #     - PRE_CREATE_DB=cadvisor
  #   ports:
  #     - "8083:8083"
  #     - "8086:8086"
  #   expose:
  #     - "8090"
  #     - "8099"
  #   volumes_from:
  #     - "influxdbData"
  #
  # cadvisor:
  #   image: google/cadvisor:v0.20.5
  #   links:
  #     - influxdb:influxsrv
  #   command: -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influxsrv:8086
  #   restart: always
  #   ports:
  #     - "8181:8080"
  #   volumes:
  #     - /:/rootfs:ro
  #     - /var/run:/var/run:rw
  #     - /sys:/sys:ro
  #     - /var/lib/docker/:/var/lib/docker:ro
  #
  # grafana:
  #   image: grafana/grafana:2.6.0
  #   restart: always
  #   links:
  #     - influxdb:influxsrv
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - HTTP_USER=admin
  #     - HTTP_PASS=admin
  #     - INFLUXDB_HOST=influxsrv
  #     - INFLUXDB_PORT=8086
  #     - INFLUXDB_NAME=cadvisor
  #     - INFLUXDB_USER=root
  #     - INFLUXDB_PASS=root
