version: '2'

volumes:
  postgresql:
  postgresql_data:

services:
  postgresd:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    restart: always
    ports:
      - "6666:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
        - postgresql:/var/lib/postgresql
        - postgresql_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    links:
      - postgresd:postgresd
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    links:
        - api:api

  proxy:
    image: nginx:latest
    ports:
        - "8080:80"   # expose frontend on 80
        - "9999:9999" # expose api for debug purposes
        - "443:443"
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
    links:
        - api:api
